#标注好的雷达点路径
lidar_out: "./sign/lidar_point_huandai.txt"
#标注好的图片点路径
photo_out: "./sign/photo_point_huandai.txt"
#雷达pcd文件夹路径
lidar_dir: "./example/huandai/lidar"
#图片文件夹路径
image_dir: "./example/huandai/photo"
#展开图文件夹路径
erp_image_dir: "./example/huandai/new_unfold"
#外参保存路径
extrinsic_out: "./result/extrinsic_huandai.txt"
#内参路径
intrinsics_path: "./sign/int_huandai.txt"
#优化后内参保存路径
intrinsics_better: "./result/ocam_refined_huandai.txt"
