#标注好的雷达点路径
lidar_out: "./sign/lidar_point_pianzhen.txt"
#标注好的图片点路径
photo_out: "./sign/photo_point_pianzhen.txt"
#雷达pcd文件夹路径
lidar_dir: "./example/pianzhen/lidar"
#图片文件夹路径
image_dir: "./example/pianzhen/photo"
#外参保存路径
extrinsic_out: "./result/extrinsic_pianzhen.txt"
#内参路径
intrinsics_path: "./sign/int_pianzhen.txt"
#投影模型
projection_model: "pinhole"
#图片宽
image_width: 1224
#图片高
image_height: 1024